const express = require('express')
const router = express.Router()
const userController = require('./controllers/users')
const questionController = require('./controllers/questions')
const submissionController = require('./controllers/submissions')
const adminController = require('./controllers/admin')
const services = require('./services/users')
const upload = require('./middleware/upload')

router.post('/login', (req, res) => services.loginService(req, res))
router.post('/register', (req, res) => services.registerService(req, res))
router.put('/user/:id', (req, res) => userController.updateUserController(req, res))
router.put('/password/:id', (req, res) => userController.updatePasswordController(req, res))
router.get('/all-users', (req, res) => userController.getUsersController(req, res))
router.get('/user', (req, res) => userController.getUserController(req, res))
router.post('/profile-upload', upload, (req, res) => userController.profileUploadController(req, res))
router.put('/update-group', (req, res) => userController.updateGroupController(req, res))
router.get('/score-board/:status', (req, res) => userController.getScoreBoardController(req, res))
router.delete('/del-user', (req, res) => userController.deleteUserController(req, res))

router.post('/add-question', (req, res) => questionController.addQuestionController(req, res))
router.put('/update-question/:id', (req, res) => questionController.editQuestionController(req, res))
router.get('/question-id/:userId/:questionId', (req, res) => questionController.getQuestionByIdController(req, res))
router.get('/all-questions', (req, res) => questionController.getQuestionController(req, res))
router.delete('/del-question/:id', (req, res) => questionController.deleteQuestionController(req, res))
router.get('/grader-question', (req, res) => questionController.graderGetQuestionController(req, res))

router.get('/sub-code', (req, res) => submissionController.getSubmissionCodeController(req, res))
router.get('/finish-sub', (req, res) => submissionController.getFinishSubmissionCodeController(req, res))
router.get('/submission', (req, res) => submissionController.getSubmissionController(req, res))
router.post('/submit', (req, res) => submissionController.fetchSubmissionController(req, res))

router.post('/question-check', (req, res) => adminController.checkQuestionController(req, res))
router.put('/question-recheck', (req, res) => adminController.recheckQuestionController(req, res))
router.get('/leader', (req, res) => adminController.getLeaderController(req, res))

module.exports = router